esphome:
  name: roomba
  platform: ESP8266
  board: d1_mini
  includes:
    - ESPHomeRoombaComponent.h
  libraries:
    - Roomba=https://github.com/Apocrathia/Roomba
  platformio_options:
    build_flags: -D HAVE_HWSERIAL0

substitutions:
  name: "roomba"
  # BRC pin, polling interval in milliseconds
  init: 'RoombaComponent::instance(D5, 1000);'

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:

ota:

custom_component:
  - lambda: |-
      auto r = ${init}
      return {r};
sensor:
 - platform: custom
   lambda: |-
      auto r = ${init}
      return {r->distanceSensor, r->voltageSensor, r->currentSensor, r->chargeSensor, r->capacitySensor, r->batteryPercentSensor};
   sensors:
     - name: "${name} distance"
       unit_of_measurement: "mm"
       accuracy_decimals: 0
     - name: "${name} voltage"
       unit_of_measurement: "mV"
       accuracy_decimals: 0
     - name: "${name} current"
       unit_of_measurement: "mA"
       accuracy_decimals: 0
     - name: "${name} charge"
       unit_of_measurement: "mAh"
       accuracy_decimals: 0
     - name: "${name} capacity"
       unit_of_measurement: "mAh"
       accuracy_decimals: 0
     - name: "${name} battery"
       unit_of_measurement: "%"
       accuracy_decimals: 0
       
text_sensor:
  - platform: custom
    lambda: |-
      auto r = ${init}
      return {r-> chargingSensor, r->activitySensor};
    text_sensors:
      - name: "${name} charging state"
      - name: "${name} activity"